# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

	Ingredient.create(:ingredient_type => "Veg")
	Ingredient.create(:ingredient_type => "Non-veg")
	Ingredient.create(:ingredient_type => "Egg")

	ProductType.create(:product_type => "Sweet")
	ProductType.create(:product_type => "Savory")
	ProductType.create(:product_type => "Bread")

	Product.create(:product_name => "Croissant chicken", :price => 40, :best_seller => false, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product1", :ingredient_id => 2, :product_type_id => 2)
	Product.create(:product_name => "Croissant chicken sausage", :price => 50, :best_seller => false, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product2", :ingredient_id => 2, :product_type_id => 2)
	Product.create(:product_name => "Croissant butter", :price => 30, :best_seller => true, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product3", :ingredient_id => 1, :product_type_id => 2)
	Product.create(:product_name => "Croissant chocolate", :price => 30, :best_seller => false, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product4", :ingredient_id => 1, :product_type_id => 1)

	Product.create(:product_name => "Bun paneer", :price => 50, :best_seller => true, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product5", :ingredient_id => 1, :product_type_id => 2)
	Product.create(:product_name => "Bun chicken sausage", :price => 50, :best_seller => true, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product6", :ingredient_id => 2, :product_type_id => 2)

	Product.create(:product_name => "Cinnamon roll", :price => 30, :best_seller => false, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product7", :ingredient_id => 3, :product_type_id => 1)
	Product.create(:product_name => "Blueberry muffin", :price => 30, :best_seller => true, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product8", :ingredient_id => 1, :product_type_id => 1)
	Product.create(:product_name => "Chocolate muffin", :price => 30, :best_seller => false, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product9", :ingredient_id => 1, :product_type_id => 1)
	Product.create(:product_name => "Chocolate lava cake", :price => 40, :best_seller => true, :description1 => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :description2 =>  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", :image => "product1", :ingredient_id => 1, :product_type_id => 1)